In [1]:
import logging

logging.basicConfig(level=logging.DEBUG, format='%(message)s')

logging.debug('Hello Debug')
logging.info('Hello Info')
logging.warning('Hello Warning')
logging.error('Hello Error')
logging.critical('Hello Critical')

Hello Debug
Hello Info
Hello Warning
Hello Error
Hello Critical


In [39]:
from io import open
import glob
import os
import numpy as np
import math
from collections import OrderedDict
import torch
import torchvision
import heapq

In [3]:
punctuation_letter = ",./;'[]<>?:\"\{\}!@#$%^&*()_+-=~`"

In [4]:
def findFiles(path):
    return glob.glob(path)

In [5]:
def removeLetter(inputStr, removeLetter):
    for i in removeLetter:
        inputStr = inputStr.replace(i, "")
    
    return inputStr

# unit test of removeLetter
if __debug__:
    oldstr = "Men Mon"
    logging.debug(oldstr)
    logging.debug(removeLetter(oldstr, "e "))

Men Mon
MnMon


In [6]:
def lowerCase(inputStr):
    return inputStr.lower()

# unit test of lowerCase
if __debug__:
    oldstr = "Men Mon"
    logging.debug(oldstr)
    logging.debug(lowerCase(oldstr))

Men Mon
men mon


In [7]:
def unicodeToAscii(inputStr):
    return ''.join(
        c for c in unicodedata.normalize('NFD', inputStr)
        if unicodedata.category(c) != 'Mn'
        and c in all_letters
    )

In [8]:
def readLines(filename):
    lines = open(filename, encoding='utf-8').read().strip().split('\n')
    return [line for line in lines if line != '']
    # return lines

if __debug__:
    all_lines = []
    
    for filename in findFiles('textFile/*.txt'):
        lines = readLines(filename)
        logging.debug('lines: {}'.format(lines))
        all_lines = all_lines + lines
    
    logging.debug('all_lines: {}'.format(all_lines))

lines: ['his is a test.', 'Test .', 'Test ?', 'Test /', 'Test "', 'Test :']
lines: ['I am here.', 'I am not there.', 'WHere are you?', 'Where is she?']
lines: ['This is a dog.', 'This is a cat.', 'Dog is not a cat.']
all_lines: ['his is a test.', 'Test .', 'Test ?', 'Test /', 'Test "', 'Test :', 'I am here.', 'I am not there.', 'WHere are you?', 'Where is she?', 'This is a dog.', 'This is a cat.', 'Dog is not a cat.']


In [9]:
def readWords(filename):
    lines = open(filename, encoding='utf-8').read().strip().split('\n')
    words = []
    for line in lines:
        line = removeLetter(line, punctuation_letter)
        if line != '':
            words = words + lowerCase(line).strip().split(' ')
    return words

if __debug__:
    all_words = []
    
    for filename in findFiles('textFile/*.txt'):
        words = readWords(filename)
        logging.debug('words: {}'.format(words))
        all_words = all_words + words
    
    logging.debug('all_words: {}'.format(all_words))

words: ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test']
words: ['i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she']
words: ['this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']
all_words: ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test', 'i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she', 'this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']


In [10]:
def sortedUniqueWords(wordList):
    return(np.unique(sorted(wordList)))
    
if __debug__:
    all_words = []
    
    for filename in findFiles('textFile/*.txt'):
        words = readWords(filename)
        logging.debug('words: {}'.format(words))
        all_words = all_words + words
    
    logging.debug('all_words: {}'.format((all_words)))
    
    unique_sorted_all_words = sortedUniqueWords(all_words)
    logging.debug('unique_sorted_all_words: {}'.format(unique_sorted_all_words))

words: ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test']
words: ['i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she']
words: ['this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']
all_words: ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test', 'i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she', 'this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']
unique_sorted_all_words: ['a' 'am' 'are' 'cat' 'dog' 'here' 'his' 'i' 'is' 'not' 'she' 'test'
 'there' 'this' 'where' 'you']


In [11]:
#
# words_in_a_document: collects of words. each collect corresponding to its own document
# sorted_unique_all_words: sorted bag of words
# allWordCount: two dimension of order dictionary. dimension 0 corrsponding to document.
#               dimension 1 corresponding to word count in the document with <key, value> = <word, word count> pairs.
#               a special key 'LENGTH' record total word counts
#

all_words = []
words_in_a_document = {}
    
for filename in findFiles('textFile/*.txt'):
    words = readWords(filename)
    logging.debug('file: {}'.format(filename))
    logging.debug('words: {}'.format(words))
    words_in_a_document[os.path.splitext(os.path.basename(filename))[0]] = words
    all_words = all_words + words
    
logging.debug('\nwords_in_a_document: {}'.format((words_in_a_document)))

logging.debug('\nall_words: {}'.format((all_words)))    
sorted_unique_all_words = sortedUniqueWords(all_words)
logging.debug('sorted_unique_all_words: {}'.format(sorted_unique_all_words))
    
all_word_count = OrderedDict()
    
for document in words_in_a_document:
    words = words_in_a_document[document]
    wordCount = OrderedDict()
    wordCount['LENGTH'] = len(words)
    for w in sorted_unique_all_words:
        # logging.debug("{}: {} times".format(w, words.count(w)))
        wordCount[w] = words.count(w)
    all_word_count[document] = wordCount

logging.debug("\nall_word_count")
logging.debug(all_word_count)

file: textFile\test 1.txt
words: ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test']
file: textFile\test 2.txt
words: ['i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she']
file: textFile\test 3.txt
words: ['this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']

words_in_a_document: {'test 1': ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test'], 'test 2': ['i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she'], 'test 3': ['this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']}

all_words: ['his', 'is', 'a', 'test', 'test', 'test', 'test', 'test', 'test', 'i', 'am', 'here', 'i', 'am', 'not', 'there', 'where', 'are', 'you', 'where', 'is', 'she', 'this', 'is', 'a', 'dog', 'this', 'is', 'a', 'cat', 'dog', 'is', 'not', 'a', 'cat']
sorted_unique_all_words: ['a' 'am' 'are' 'cat' 'dog' 'here' 'his' 'i' 'is' 'not' 'she' 'test'
 'there' 

In [12]:
#
# count words tf, words_tf
#

words_tf = OrderedDict()
num_bow = len(sorted_unique_all_words)
logging.debug("number of bag of words: {}\n".format(num_bow))

for document in all_word_count:
    tf = OrderedDict()
    for word in all_word_count[document]:
        if word != 'LENGTH':
            tf[word] = (all_word_count[document][word] + 1) / (all_word_count[document]['LENGTH'] + num_bow)
    logging.debug("document {}".format(document))
    logging.debug("{}\n".format(tf))
    words_tf[document] = tf
logging.debug("words tf")
logging.debug("{}\n".format(words_tf))

number of bag of words: 16

document test 1
OrderedDict([('a', 0.08), ('am', 0.04), ('are', 0.04), ('cat', 0.04), ('dog', 0.04), ('here', 0.04), ('his', 0.08), ('i', 0.04), ('is', 0.08), ('not', 0.04), ('she', 0.04), ('test', 0.28), ('there', 0.04), ('this', 0.04), ('where', 0.04), ('you', 0.04)])

document test 2
OrderedDict([('a', 0.034482758620689655), ('am', 0.10344827586206896), ('are', 0.06896551724137931), ('cat', 0.034482758620689655), ('dog', 0.034482758620689655), ('here', 0.06896551724137931), ('his', 0.034482758620689655), ('i', 0.10344827586206896), ('is', 0.06896551724137931), ('not', 0.06896551724137931), ('she', 0.06896551724137931), ('test', 0.034482758620689655), ('there', 0.06896551724137931), ('this', 0.034482758620689655), ('where', 0.10344827586206896), ('you', 0.06896551724137931)])

document test 3
OrderedDict([('a', 0.13793103448275862), ('am', 0.034482758620689655), ('are', 0.034482758620689655), ('cat', 0.10344827586206896), ('dog', 0.10344827586206896), ('he

In [13]:
#
# count words idf, words_idf
#

words_idf = OrderedDict()
documents = len(all_word_count)

for word in sorted_unique_all_words:
    doc_count = 1
    for document in all_word_count:
        if all_word_count[document][word] != 0:
            doc_count = doc_count + 1
    logging.debug("word {}\'s document count = {}".format(word, doc_count))
    words_idf[word] = (documents + 1) / doc_count
logging.debug("\nwords idf")
logging.debug(words_idf)

word a's document count = 3
word am's document count = 2
word are's document count = 2
word cat's document count = 2
word dog's document count = 2
word here's document count = 2
word his's document count = 2
word i's document count = 2
word is's document count = 4
word not's document count = 3
word she's document count = 2
word test's document count = 2
word there's document count = 2
word this's document count = 2
word where's document count = 2
word you's document count = 2

words idf
OrderedDict([('a', 1.3333333333333333), ('am', 2.0), ('are', 2.0), ('cat', 2.0), ('dog', 2.0), ('here', 2.0), ('his', 2.0), ('i', 2.0), ('is', 1.0), ('not', 1.3333333333333333), ('she', 2.0), ('test', 2.0), ('there', 2.0), ('this', 2.0), ('where', 2.0), ('you', 2.0)])


In [47]:
#
# count words tfidf, words_tfidf in python dictionary implementation
# also tfidf_array in python numpy array implementation
#

words_tfidf = OrderedDict()
print(len(all_word_count))
print(len(sorted_unique_all_words))
tfidf_array = np.zeros([len(all_word_count), len(sorted_unique_all_words)])
print(tfidf_array)

document_index = 0
for document in all_word_count:
    tfidf = OrderedDict()
    word_index = 0
    for word in all_word_count[document]:
        if word != 'LENGTH':
            # logging.debug("tf: {:.6f}, idf: {:.6f}, log of tf: {:.6f}, log of idf: {:.6f}, (1+logtf)*logidf: {:.6f}".format(
            #    words_tf[document][word], words_idf[word],
            #    math.log(words_tf[document][word]), math.log(words_idf[word]),
            #    (1 + math.log(words_tf[document][word])) * math.log(words_idf[word])))
            tfidf[word] = (1 + math.log(words_tf[document][word])) * math.log(words_idf[word])
            tfidf_array[document_index][word_index] = tfidf[word]
            word_index = word_index + 1
            
    logging.debug("document {}".format(document))
    logging.debug("{}\n".format(tfidf))
    words_tfidf[document] = tfidf
    document_index = document_index + 1
    
logging.debug("words tfidf")
logging.debug("{}\n".format(words_tfidf))
logging.debug("{}\n".format(tfidf_array))

document test 1
OrderedDict([('a', -0.43892477839364497), ('am', -1.5380075220200162), ('are', -1.5380075220200162), ('cat', -1.5380075220200162), ('dog', -1.5380075220200162), ('here', -1.5380075220200162), ('his', -1.057554508101815), ('i', -1.5380075220200162), ('is', -0.0), ('not', -0.6383307958112386), ('she', -1.5380075220200162), ('test', -0.1892053885793429), ('there', -1.5380075220200162), ('this', -1.5380075220200162), ('where', -1.5380075220200162), ('you', -1.5380075220200162)])



3
16
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


TypeError: 'tuple' object does not support item assignment

In [25]:
#
# print out word's tf.idf
#

print("{:20s}".format(""), end='')
for document in words_tfidf:
    print("{:20s}".format(document), end='')
print("")
for word in sorted_unique_all_words:
    print("{:10s}".format(word), end='')
    for document in words_tfidf:
        print("{:20.10f}".format(words_tfidf[document][word]), end='')
    print("")

                    test 1              test 2              test 3              
a                -0.4389247784       -0.6810285705       -0.2822165356
am               -1.5380075220       -0.8793844197       -1.6408844301
are              -1.5380075220       -1.1604314162       -1.6408844301
cat              -1.5380075220       -1.6408844301       -0.8793844197
dog              -1.5380075220       -1.6408844301       -0.8793844197
here             -1.5380075220       -1.1604314162       -1.6408844301
his              -1.0575545081       -1.6408844301       -1.6408844301
i                -1.5380075220       -0.8793844197       -1.6408844301
is               -0.0000000000       -0.0000000000       -0.0000000000
not              -0.6383307958       -0.4816225531       -0.4816225531
she              -1.5380075220       -1.1604314162       -1.6408844301
test             -0.1892053886       -1.6408844301       -1.6408844301
there            -1.5380075220       -1.1604314162       -1.6408844

In [50]:
#
# show top k tfidf words in document
#

#print(OrderedDict(sorted(k.items(), key=lambda t: t[1])))

top_k = 3
for i in range(np.shape(tfidf_array)[0]):
    # logging.debug(heapq.nlargest(3, range(len(tfidf_array[i])), tfidf_array[i].__getitem__))
    # print(words_tfidf[i])
    logging.debug(sorted_unique_all_words[heapq.nlargest(top_k, range(len(tfidf_array[i])), tfidf_array[i].__getitem__)])

['is' 'test' 'a']
['a' 'am' 'are']
['a' 'am' 'are']
